### ISSUE TITLE
New failure when compiling on u16 (xenial ) and u18 (bionic)

### ISSUE THREAD

**Issue by phrocker** [libressl-portable/openbsd#106]
This commit has caused us to have travis failures on our project (https://github.com/libressl-portable/openbsd/commit/136e6c997f476cc65e614e514ac3bf6ee54fc4b4#diff-a070a70a1a6116c26904fcfe70c5d320R62 ). Seems that sys/limits.h cannot be found with the current linking. Switching to <limits.h> of course solves it

**Comment by 4a6f656c** [comment]
Committed upstream - thanks.

While you're more than welcome to run travis against LibreSSL -current, do be aware that these kinds of things will occur from time-to-time, particularly during development peaks. If you want to avoid these issues then using a LibreSSL portable release might be a better option for you. Otherwise, feel free to keep the fixes coming :)

**Comment by phrocker** [comment]
I added https://github.com/libressl-portable/portable/issues/512 as we previously used a release and ran into issues; however, I didn't try a prior release. I will try v2.8.0 Thanks!
