### ISSUE TITLE
LibreSSL 2.2.2 compile fails with "Error: no such instruction" on KVM Virtual CPU

### ISSUE THREAD

**Issue by sysfu** [libressl-portable/openbsd#40]
Have built many previous versions of LibreSSL on the same system without issue, so it seems the offending commit was introduced in the last release.

Error:
```
$ make check
Making check in crypto
  CCAS     aes/aes-elf-x86_64.lo
  CCAS     aes/bsaes-elf-x86_64.lo
  CCAS     aes/vpaes-elf-x86_64.lo
aes/vpaes-elf-x86_64.s: Assembler messages:
aes/vpaes-elf-x86_64.s:172: Error: no such instruction: `palignr $12,%xmm5,%xmm5'
aes/vpaes-elf-x86_64.s:298: Error: no such instruction: `palignr $8,%xmm6,%xmm0'
aes/vpaes-elf-x86_64.s:436: Error: no such instruction: `palignr $15,%xmm8,%xmm1'
aes/vpaes-elf-x86_64.s:437: Error: no such instruction: `palignr $15,%xmm8,%xmm8'
aes/vpaes-elf-x86_64.s:442: Error: no such instruction: `palignr $1,%xmm0,%xmm0'
*** Error 1 in crypto (Makefile:7479 'aes/vpaes-elf-x86_64.lo': @echo "  CCAS    " aes/vpaes-elf-x86_64.lo;/bin/sh ../libtool --silent    --...)
*** Error 1 in /usr/local/src/libressl-2.2.2 (Makefile:476 'check-recursive')
```

System Info:
```
$ uname -a
OpenBSD <hostname> 5.7 GENERIC#2 amd64
$ dmesg|grep cpu
cpu0 at mainbus0: apid 0 (boot processor)
cpu0: Virtual CPU e7da7129d3ee, 3600.46 MHz
cpu0: FPU,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,MMX,FXSR,SSE,SSE2,HTT,SSE3,PCLMUL,SSSE3,FMA3,CX16,PCID,SSE4.1,SSE4.2,x2APIC,MOVBE,POPCNT,DEADLINE,AES,XSAVE,AVX,RDRAND,HV,NXE,LONG,LAHF,FSGSBASE,BMI1,HLE,AVX2,SMEP,BMI2,ERMS,INVPCID,RTM
cpu0: 64KB 64b/line 2-way I-cache, 64KB 64b/line 2-way D-cache, 512KB 64b/line 16-way L2 cache
cpu0: ITLB 255 4KB entries direct-mapped, 255 4MB entries direct-mapped
cpu0: DTLB 255 4KB entries direct-mapped, 255 4MB entries direct-mapped
cpu0: smt 0, core 0, package 0
cpu0: apic clock running at 1000MHz
acpicpu0 at acpi0
```

**Comment by bob-beck** [comment]
You need to update your binutils to use a modern AS to compile it..

You can either update to current, (which will compile it) or use -no-asm
for a workaround.

**Comment by sysfu** [comment]
Thank you for the lightning quick response. I was able to use the '--disable-asm' configure script option to workaround the issue on the existing 5.7-release system.

```
./configure --disable-asm
make check
sudo make install
```

**Comment by romario89** [comment]
I use a Mac mini late 2009 w. Snow Leopard and would like to compile libressl with aes-ni. I've upgraded to latest version of GNU binutils but still I get **"no such instruction: `aesenc %xmm1,%xmm2"** erro during the compilation of:

** CPPAS    aes/libcrypto_la-aesni-macosx-x86_64.lo**

Specifically it happens during the compilation of the 14th line of:

**./crypto/aes/aesni-macosx-x86_64.S**

and it begins with:

    L$oop_enc1_1:
    	aesenc	%xmm1,%xmm2
    	decl	%eax
    	movups	(%rdx),%xmm1
    	leaq	16(%rdx),%rdx
    	jnz	L$oop_enc1_1	
    	aesenclast	%xmm1,%xmm2
    	movups	%xmm2,(%rsi)
    	retq

Apperantly the GNU AS (Apple Inc version cctools-773~33, GNU assembler version 1.38) or the latest GNU Binutils version 2.25 are simplu unable to compile these aes-ni specific instructions.


Sure, I could pass this step with **"--no-asm"** directive but I'd like to compile it with assembly codes. The Mac mini in question does support AES-NI set because on the same exact machine with an OS X Lion harddisk, those lines got compiled in a heartbeat. So it looks like an issue with the OS. I was wondering if some configure options or some environment variables could make them compile? Any advice is appreciated. Thanks.

**Comment by busterb** [comment]
You could revert commit https://github.com/libressl-portable/openbsd/commit/350542f2b in the openbsd repo and regenerate the .S if you're just interested in the retro-computing novelty. I'll assume you understand the risks of continuing to use that OS.

**Comment by romario89** [comment]
Thank you for the comment. Does that commit produce the same code as the one which is produced with the **--no-asm** directive during configure or does it mimic the functionality of the aes-ni instructions by replacing the aes-ni codes with some x86_64 compatible assembly codes? Just wondering.

**Comment by busterb** [comment]
It inserts raw aes-ni machine code instead of passing the opcodes to the assembler, so it more-or-less produces the same results, though I couldn't guarantee it produces exactly the same binary code.

**Comment by romario89** [comment]
That sounds good. I will give it a try.
