### ISSUE TITLE
X509_cmp_time fails for dates that don't fit in time_t

### ISSUE THREAD

**Issue by fancycode** [libressl-portable/openbsd#66]
In https://github.com/libressl-portable/openbsd/commit/de5a7bf9d95b8cfa44465f9b436a6feaed026cdb#diff-c72c45bb1891a4148a352b678fe463d4 `X509_cmp_time` has changed in that the string must be representable by `time_t`.

This causes it to fail for large dates on 32bit platforms (tested on Ubuntu) where `time_t` is 32bit causing certificates that have a really far future expiration (e.g. 100 years from now) to no longer verify successfully.

Such certificates verify with OpenSSL/BoringSSL.

**Comment by bob-beck** [comment]
There is no reason for a modern 32 bit platform to have a 32 bit time_t - if it is your operating system is going to be badly broken on dates in the near future - i.e. after January 18, 2038

In a nutshell, OpenSSL is failing defensively, because your operating system is fundamentally broken for these dates, and you will very likely have security problems
dealing with and accepting and manipulating such dates..  Really, this is an issue that
the underlying operating system needs to fix - to avoid many other problems (even if we accept the certificate).

**Comment by bob-beck** [comment]
And in case you're wondering, I'm of an age where some jerk might end up putting some embedable linux 32 bit internet-of-shite thing in my chest as a pacemaker or something before Jan 19 2038.. I'm not going to get killed by a crappy linux freaking out then because I didn't to my darndest to get the ecosystem to fix it's problems.  I want to die from my own foolish excesses.

**Comment by fancycode** [comment]
Thanks for your delightful response. Lets hope you (or me for that matter) will never need a pacemaker ;-)

Unfortunately the software I wanted to build against LibreSSL is running with Ubuntu Trusty on armhf which only has a 32bit `time_t` - I guess I'll have to stick with OpenSSL/BoringSSL for now then.

Anyway, thanks for your feedback and sorry for bothering you.

**Comment by chneukirchen** [comment]
AFAICS, this is being worked around in 362ffef32c0fcae703d57838e9f5704240a63213

**Comment by 4a6f656c** [comment]
@chneukirchen - correct, the notafter date is now clamped to 2038 in the case of a 32-bit time_t.
