### ISSUE TITLE
Implement SSL_CTX_get_tlsext_status_cb

### ISSUE THREAD

**Issue by Sp1l** [libressl-portable/openbsd#83]
Allow access to tlsext_status_cb
This is a feature used in haproxy. Current [patch](https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/ports/net/haproxy/patches/patch-src_ssl_sock_c?rev=1.7&content-type=text/plain) (by me?) is also in OpenBSD ports and does not do what you'd want it to do...

**Comment by 4a6f656c** [comment]
We will likely do this, however it is kinda crazy that an application would set a callback and then forget that it set a callback and needs to retrieve it via an API...

Also, that patch is actually dangerous - non-existent control values should not just be defined since there is a reason why the control value is missing. While we typically reuse the same control values as OpenSSL, there is no guarantee that we will, so a completely different control could be triggered instead of the one that is intended (and unimplemented).

**Comment by kinichiro** [comment]
https://github.com/libressl-portable/openbsd/commit/6bb43288a517595b093f0fa0a10c4f7c1d123464 fixed this issue.

**Comment by kinichiro** [comment]
@Sp1l Can you close this issue ?

**Comment by busterb** [comment]
I think we can just close it. Thanks.
