### ISSUE TITLE
Invalid command 'SSLOpenSSLConfCmd' in Apache 2.4 with LRE 2.6.3 for Windows

### ISSUE THREAD

**Issue by long76** [libressl-portable/openbsd#86]
Lines(in httpd-ssl.conf file):
SSLOpenSSLConfCmd ECDHParameters prime256v1
SSLOpenSSLConfCmd Curves brainpoolP512r1:secp521r1:brainpoolP384r1:secp384r1:brainpoolP256r1:prime256v1
does't work,
how i can set for all vhosts ECDHParameters and Curves? 
thanks.
Apache was downloaded from Apachehaus.

**Comment by kinichiro** [comment]
Please post an issue (or patch) on portable repo, since here is just a mirror of the current OpenBSD CVS tree.

SSLOpenSSLConfCmd is available in httpd 2.4.8 and later, if using OpenSSL 1.0.2 or later.
https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslopensslconfcmd

LibreSSL forked from OpenSSL 1.0.1, and doesn't have SSL_CONF_cmd(3).
I don't think that directive does not work with LibreSSL.

**Comment by long76** [comment]
ok
