### ISSUE TITLE
Second colon sign in the URL break things

### ISSUE THREAD

**Issue by chainikdn** [libressl-portable/openbsd#90]
Plex Media Player (which is based on libmpv based on ffmpeg built with libtls) uses URLs like this:
`https://192.168.1.5:32400/video/:/transcode/universal/start?hasMDE=1&...`

And mpv gives the following error:
`2018-02-11 15:56:06 [ ERROR ] PlayerComponent.cpp @ 589 - ffmpeg: tls: server name not specified `

I believe this's because the unneeded check for a 2nd colon in https://github.com/libressl-portable/openbsd/blob/master/src/lib/libtls/tls_util.c

```
/* Find the port seperator. */
if ((p = strchr(p, ':')) == NULL)
	goto done;

/* If there is another separator then we have issues. */
if (strchr(p + 1, ':') != NULL)
	goto done;
```

**Comment by 4a6f656c** [comment]
This is more likely a bug or misconfiguration in the code the that is using libtls - the error is caused by no server name being specified, yet verification is enabled. I believe the code in question is:

https://gitlab.com/alelec/FFmpeg/blob/master/libavformat/tls_libtls.c#L121

And in this case, with a numeric host (192.168.1.5 in your above example), it passes NULL as the server name to `tls_connect_cbs`, which will cause the `server name not specified` failure. If the IP address exists in the certificate, then it should be passed through as the server name. Otherwise, the only other option would be to disable name verification for the certificate.

For the record, `tls_host_port()` is not involved here - it is only called for `tls_connect()` and `tls_connect_servername()`. Also, the second colon check is very much necessary.

**Comment by chainikdn** [comment]
Thanks, this's it.
One possible solution:
```
--- a/libavformat/tls_libtls.c  2018-02-19 18:33:28.485092988 +0300
+++ b/libavformat/tls_libtls.c  2018-02-19 22:23:09.004103503 +0300
@@ -109,7 +109,7 @@
         goto err_config;
     if (c->key_file && tls_config_set_key_file(cfg, c->key_file) == -1)
         goto err_config;
-    if (!c->verify) {
+    if (!c->verify || c->numerichost) {
         tls_config_insecure_noverifycert(cfg);
         tls_config_insecure_noverifyname(cfg);
         tls_config_insecure_noverifytime(cfg);
```
