### ISSUE TITLE
overflow() at realpath.c

### ISSUE THREAD

**Issue by RootUp** [libressl-portable/openbsd#97]
Team, 

File: /openbsd/blob/master/src/lib/libc/stdlib/realpath.c#L46

i.e
`realpath(const char *path, char *resolved)`

According to the documentation of `realpath()` the output buffer needs to be at least of size `PATH_MAX` specifying output buffers large enough to handle the maximum-size possible result from path manipulation functions. (In that instance, buf's size comes from `uv__fs_pathmax_size()`. That function attempts to use `pathconf(path, _PC_PATH_MAX)` as noted in the realpath(3) docs)

But over here `uv__fs_pathmax_size()` nor `pathconf(path, _PC_PATH_MAX)` is used.

Passing an inadequately-sized output buffer to a path manipulation function can result in a buffer overflow. Such functions include `realpath()` `readlink()` `PathAppend()` and others.

Not Sure about this:  However, I also see `getcwd()` in use, usage of `getcwd()` by `realpath()` which can be used to write before the destination buffer leading to a buffer underflow and potential code execution. - CVE-2018-1000001

**Comment by RootUp** [comment]
My bad, I did a comprehensive review again I don't feel its a bug over here.
Thoughts anyone?

**Comment by botovq** [comment]
On Sat, Jul 14, 2018 at 07:43:04AM -0700, Dhiraj Mishra wrote:
> My bad, I did a comprehensive review again I don't feel its a bug over here.
> Thoughts anyone?

You still haven't told us where "over here" is.

In your previous comment you referred to some stuff from POSIX, quoted
text verbatim from https://cwe.mitre.org/data/definitions/785.html
without reference, talked about a libuv-specific function without making
clear why and referred to some linux docs of realpath.

All this while linking to a copy of OpenBSD's realpath that just happens
to be there since the whole stdlib directory is this repo.

If you think you have found a bug in realpath(3), please mail to
bugs@openbsd.org and please be specific about what that bug is.
